### ISSUE TITLE
sdfiles::rmdir() doesn't work as expected

### ISSUE THREAD

**Issue by konimaru** [uli/basicengine-firmware#27]
```mkdir "some_name"``` creates a directory in the CWD. Removing said directory with ```rmdir "some_directory"``` does not work (I get font corruption which is cured by calling e.g. ```files``` again).

The directory can in fact only be removed with ```rmdir "/sd/some_directory"```.

**Comment by konimaru** [comment]
Font corruption is most likely due erroring out after SD_BEGIN() without matching SD_END().

**Comment by konimaru** [comment]
Fixed locally (pending verification).

**Comment by bitartrate** [comment]
In the official nightly build I have verified the font corruption but rmdir "/sd/some_directory" did not remove the directory for me.
I cloned your repo with git clone --branch rmdir http://github.com/konimaru/basicengine-firmware.git
But I still see the font corruption with rmdir"some_directory"
With this build the rmdir"/sd/some_directory" did remove the directory though.

**Comment by konimaru** [comment]
Well that would be because I haven't committed any changes yet :)

**Comment by bitartrate** [comment]
You did say 'locally', didn't you :)  ::palm face::

**Comment by bitartrate** [comment]
I have confirmed that rmdir does work as intended by this fix.
